### ISSUE TITLE
Enforce consistent code style

### ISSUE THREAD

**Issue by jamietanna** [valfirst/slf4j-test#185]
Keeping consistent code style is hard - especially for new contributors to a project.

Would you be happy with an enforced code style, perhaps via the [Spotless Gradle plugin](https://github.com/diffplug/spotless/tree/HEAD/plugin-gradle), which allows folks to easily apply code style changes through `./gradlew spotlessApply`, instead of needing any other local setup?

If so, are there any preferences you would have? I.e. are you happy with Google Java code style, or would another style be preferable?

**Comment by valfirst** [comment]
I totally agree with introducing code style (it was on my virtual roadmap 😉).

Spotless is a good start in terms of efforts vs speed. Since the project is still maven-based, we need to use [Spotless Maven plugin](https://github.com/diffplug/spotless/tree/main/plugin-maven). But AFAIK Spotless won't be able to cover all variety of ways how the code could be written, so I was also thinking about [Checkstyle](https://checkstyle.sourceforge.io/).

As for code style configuration I believe Google Java code style should be good to inherit and then to tune it upon the needs. In short I'm ok with any configuration that will match the current codebase state better than other configurations.

**Comment by jamietanna** [comment]
Ah yes, sorry should've said Maven :sweat_smile:

> But AFAIK Spotless won't be able to cover all variety of ways how the code could be written

What do you mean, sorry?

> As for code style configuration I believe Google Java code style should be good to inherit and then to tune it upon the needs. In short I'm ok with any configuration that will match the current codebase state better than other configurations.

Sure thing - I can have a look at getting Google Java code style set up with 4 spaces and will raise a draft PR to see your thoughts

**Comment by valfirst** [comment]
> What do you mean, sorry?

Spotless provides several ways how to [format/clean code](https://github.com/diffplug/spotless#current-feature-matrix). And its key feature is auto-fix. At the same other time static code analysis tools like Checktyle have more [fine-grained checks](https://checkstyle.sourceforge.io/checks.html), but they can't fix violations in fully-automated fashion.

> Sure thing - I can have a look at getting Google Java code style set up with 4 spaces and will raise a draft PR to see your thoughts

Please go ahead with Spotless, after that we'll see if any other additional analysis is needed
